<a href="https://colab.research.google.com/github/MaryamAmjad2/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


 # Creating Tensors

##Scalar Tensor

In [2]:
scalar=torch.tensor(2)
scalar

tensor(2)

In [3]:
scalar.ndim

0

##Vector Tensor

In [4]:
vector=torch.tensor([4,4])

In [5]:
print(scalar.shape)
print(vector.shape)

print(scalar.ndim)
print(vector.ndim)

torch.Size([])
torch.Size([2])
0
1


## Matrix

In [6]:
matrix=torch.tensor([
    [1,2],
    [3,4]
])
print(matrix.shape)
print(matrix.ndim)

torch.Size([2, 2])
2


## Tensor

In [7]:
TENSOR=torch.tensor([[
    [1,2,4],
    [3,4,5],
    [6,7,8]
]])

print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [8]:
TENSOR[0,1,2]

tensor(5)

In [9]:
tensor_2=torch.tensor( [
    [[1,2,3],[2,3,3]],
    [[1,2,3],[2,3,3]]
    ])
print(tensor_2.ndim)
print(tensor_2.shape)

3
torch.Size([2, 2, 3])


## Random Tensors

In [10]:
x=torch.zeros(3)
y=torch.rand(1,3,3)
print(y)
print(x)

image_size_random_tensor=torch.rand(size=(224,224,3)) ## h,w, color channel
print(image_size_random_tensor.ndim)
print(image_size_random_tensor.shape)

tensor([[[0.7464, 0.3255, 0.1784],
         [0.4365, 0.2473, 0.8710],
         [0.5070, 0.2789, 0.5517]]])
tensor([0., 0., 0.])
3
torch.Size([224, 224, 3])


In [11]:
tensor_2.dtype

torch.int64

## Creating  a range of tensors and tensor like

In [12]:
TENSOR_3=torch.arange(2,10,3)
TENSOR_3

tensor([2, 5, 8])

In [13]:
TENSOR_4=torch.zeros_like(tensor_2)
TENSOR_4

tensor([[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]])

# Dealing with Tensor Data Type

In [14]:
float_32_tensor=torch.tensor([2.,3.,5.],dtype=None,device='cpu',requires_grad=True)
print(float_32_tensor)    #dtype by default if float_32 even if you set it to none

tensor([2., 3., 5.], requires_grad=True)


## Changing Data Type

In [15]:
float16_tensor=float_32_tensor.type(torch.float16)
print(float16_tensor.dtype)

torch.float16


In [16]:
print(TENSOR_4.shape)
print(TENSOR_4.size())
print(TENSOR_4.dtype)
print("Device its on",TENSOR_4.device)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.int64
Device its on cpu


# Manipulating Tensor

In [17]:
T1=torch.tensor([1,2,3])
T2=torch.rand(1,3)
print(T1)
print(T2)

tensor([1, 2, 3])
tensor([[0.5262, 0.8729, 0.3743]])


## ADD

In [18]:
T1_add_10=T1+10
print(T1_add_10)


T_add=T1+T2
print(T_add)

tensor([11, 12, 13])
tensor([[1.5262, 2.8729, 3.3743]])


## Multiply

In [19]:
T1_mul_10=T1*10
print(T1_mul_10)


T_add=T1*T2
print(T_add)

tensor([10, 20, 30])
tensor([[0.5262, 1.7458, 1.1230]])


## Torch Built in Functions

In [20]:
T3=torch.mul(T1,0)
print(T3)

T4=torch.add(T1,100)
print(T4)

T5=torch.div(T4,5)
print(T5)


tensor([0, 0, 0])
tensor([101, 102, 103])
tensor([20.2000, 20.4000, 20.6000])


## Matrix Multiplication

In [21]:
M1=torch.tensor([
    [2,3,4],
    [6,7,4]
])

M2=torch.tensor([
    [10,89,19],
    [23,6,7],
    [4,5,6]
])

# element_wise_mul=M1*M2
# print(element_wise_mul)

matrix_mul=torch.matmul(M1,M2)
print("Order is ", M1.shape, M2.shape)
print(matrix_mul)


Order is  torch.Size([2, 3]) torch.Size([3, 3])
tensor([[105, 216,  83],
        [237, 596, 187]])


## Dealing with tensor shape error

In [22]:
M3=torch.rand(3,4)
M4=torch.rand(3,4)

# M5=torch.matmul(M3,M4)    will through error

M4_transpose=M4.T
M5=torch.matmul(M3,M4_transpose)
print(M5.shape)
print(M5)



torch.Size([3, 3])
tensor([[1.1769, 0.6738, 0.9262],
        [1.1309, 0.4551, 0.8851],
        [1.0227, 0.7344, 0.7779]])


# Aggregation

In [23]:
print(torch.sum(M5))
print(torch.min(M5))
print(torch.max(M5))
print(torch.mean(M1.float()))

## or

M5.min()
M5.max()

tensor(7.7831)
tensor(0.4551)
tensor(1.1769)
tensor(4.3333)


tensor(1.1769)

## Positional min max

In [24]:
print(M5.argmax())
print(M5.argmin())

tensor(0)
tensor(4)


# Reshaping Viewing and Stacking Tensor

## Reshaping

In [25]:
M6=torch.rand(2,5)

# M6_reshaped=M6.reshape( 5,2 )
# print(M6_reshaped)
print(M6)

M6.reshape( 5,2 )
print(M6)


tensor([[0.9535, 0.0534, 0.6865, 0.5100, 0.4373],
        [0.2521, 0.4401, 0.1609, 0.0405, 0.8868]])
tensor([[0.9535, 0.0534, 0.6865, 0.5100, 0.4373],
        [0.2521, 0.4401, 0.1609, 0.0405, 0.8868]])


## Viewing

In [26]:
x=M6.view(1,10)
x[:,0]=0
print(x)
print(M6.shape)




tensor([[0.0000, 0.0534, 0.6865, 0.5100, 0.4373, 0.2521, 0.4401, 0.1609, 0.0405,
         0.8868]])
torch.Size([2, 5])


## Stacking

In [27]:
print(M5.shape)
print(M2.shape)

T_stack=torch.stack([M2,M5],dim=1)
print(T_stack)

torch.Size([3, 3])
torch.Size([3, 3])
tensor([[[10.0000, 89.0000, 19.0000],
         [ 1.1769,  0.6738,  0.9262]],

        [[23.0000,  6.0000,  7.0000],
         [ 1.1309,  0.4551,  0.8851]],

        [[ 4.0000,  5.0000,  6.0000],
         [ 1.0227,  0.7344,  0.7779]]])


## Squeeze and UnSqueeze

In [28]:
x = torch.zeros(1, 3, 2)
print(x.shape)          # torch.Size([1, 3, 1])

y = x.squeeze()
print(y.shape)           # torch.Size([3])  ← both 1's removed

torch.Size([1, 3, 2])
torch.Size([3, 2])


In [29]:
unsqueezed_y=y.unsqueeze(dim=2)
print(unsqueezed_y.shape)
print(y)

torch.Size([3, 2, 1])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


## Permute

In [30]:
print(x.shape)
Permute_x=torch.permute(x,(1,2,0))
print(Permute_x.shape)

torch.Size([1, 3, 2])
torch.Size([3, 2, 1])


## Indexing

In [31]:
arr=torch.arange(1,10).reshape(1,3,3)


arr[0]

#print(x_org)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
print(arr[0,0])
print(arr[0,0,1])

tensor([1, 2, 3])
tensor(2)


In [33]:
arr[0,:,1]

tensor([2, 5, 8])

In [34]:
arr[:,:,1:3]

tensor([[[2, 3],
         [5, 6],
         [8, 9]]])

# Pytorch Tensors and Numpy

## Changing Data from Numpy to Torch Tensor

In [35]:
np_arr=np.array([1.,2.,3.])

# Numpy Arrray default dtype if float64 and PyTorch
# tensor default dtype is float32
tensor_from_np=torch.from_numpy(np_arr).type(torch.float32)
np_arr,tensor_from_np





(array([1., 2., 3.]), tensor([1., 2., 3.]))

### if we change value of an array the tensor doesnt change

In [36]:
np_arr=np_arr+10
np_arr,tensor_from_np

(array([11., 12., 13.]), tensor([1., 2., 3.]))

## Tensor to Numpy Array


In [37]:
tensor_to_np_arr=tensor_from_np.numpy().astype(np.float64)
tensor_to_np_arr

array([1., 2., 3.])

# Reproducibility

In [38]:
torch.manual_seed(42)

T5=torch.rand(3,3)
print(T5)


torch.manual_seed(42)

T6=torch.rand(3,3)
print(T6)

print(T5==T6)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


# Check GPU Availablity

In [39]:
torch.cuda.is_available()  ## To Check

False

## Count GPU

In [40]:
torch.cuda.device_count()

0

# Device Agnostic Code

In [10]:
device='cuda' if torch.cuda.is_available() else "cpu"
device

'cuda'

# Putting Tensor and Model on GPU

In [13]:
import torch
tens=torch.tensor(2,device='cuda')

# or

tensor_to_gpu=tens.to(device)
print(tensor_to_gpu)


print(f'{tens} is on {tens.device}')

tensor(2, device='cuda:0')
2 is on cuda:0


## Putting Tensor Back to CPU

In [20]:
# tensor_to_gpu.numpy()
# This will not work cause tensor on GPU cant be converted to numpy array

In [22]:
tens_to_cpu=tensor_to_gpu.cpu()
tens_to_cpu.device
tens_to_cpu.numpy()

array(2)